"""
Master DSA dataset.

Each entry:
  name, kind (DS or Algorithm or Technique/Pattern), category, definition,
  time_complexity, space_complexity, key_techniques, wikipedia, resources,
  sean_prashad (covered?), grind75 (covered?), notes

Coverage flags:
  - sean_prashad: technique appears in Sean Prashad's pattern cheatsheet or
    is the primary technique for one of his pattern groups
  - grind75: topic appears in Grind 75's 15 categories
    (Array, Stack, Linked List, String, Binary Tree, Binary Search, Graph,
     Dynamic Programming, Binary Search Tree, Hash Table, Binary, Heap, Trie,
     Recursion, Matrix)
"""

ENTRIES = [
    # ============================================================
    # DATA STRUCTURES — Linear
    # ============================================================
    {
        "name": "Array",
        "kind": "Data Structure",
        "category": "Linear",
        "definition": "Contiguous block of memory storing fixed-size elements, accessed by integer index in O(1).",
        "time": "Access O(1) · Search O(n) · Insert/Delete O(n)",
        "space": "O(n)",
        "techniques": "Two pointers; Sliding window; Prefix sum; Difference array; In-place swap; Sorting",
        "wikipedia": "https://en.wikipedia.org/wiki/Array_(data_structure)",
        "resources": "https://www.techinterviewhandbook.org/algorithms/array/ | https://visualgo.net/en/list",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Most common interview structure. Master sliding window and two pointers first.",
    },
    {
        "name": "Dynamic Array (ArrayList / Vector)",
        "kind": "Data Structure",
        "category": "Linear",
        "definition": "Resizable array that doubles capacity on overflow giving amortized O(1) append.",
        "time": "Access O(1) · Append amortized O(1) · Insert/Delete O(n)",
        "space": "O(n)",
        "techniques": "Amortized analysis; Geometric resizing",
        "wikipedia": "https://en.wikipedia.org/wiki/Dynamic_array",
        "resources": "https://www.geeksforgeeks.org/how-do-dynamic-arrays-work/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Java ArrayList, C++ vector, Python list.",
    },
    {
        "name": "String",
        "kind": "Data Structure",
        "category": "Linear",
        "definition": "Immutable (in most languages) sequence of characters; an array of chars under the hood.",
        "time": "Access O(1) · Concat O(n) · Substring O(n)",
        "space": "O(n)",
        "techniques": "Two pointers; Sliding window; Hashing; Trie; KMP; Rabin-Karp",
        "wikipedia": "https://en.wikipedia.org/wiki/String_(computer_science)",
        "resources": "https://www.techinterviewhandbook.org/algorithms/string/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Use StringBuilder/list-join in Python/Java to avoid O(n^2) concatenation.",
    },
    {
        "name": "Linked List (Singly)",
        "kind": "Data Structure",
        "category": "Linear",
        "definition": "Chain of nodes, each holding a value and a pointer to the next node.",
        "time": "Access O(n) · Insert/Delete at head O(1)",
        "space": "O(n)",
        "techniques": "Two pointers; Fast & slow (Floyd's cycle); Dummy head; Iterative reverse",
        "wikipedia": "https://en.wikipedia.org/wiki/Linked_list",
        "resources": "https://www.techinterviewhandbook.org/algorithms/linked-list/ | https://visualgo.net/en/list",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If given a linked list → Two pointers.'",
    },
    {
        "name": "Doubly Linked List",
        "kind": "Data Structure",
        "category": "Linear",
        "definition": "Linked list where each node has prev and next pointers, enabling O(1) deletion given a node.",
        "time": "Access O(n) · Insert/Delete given node O(1)",
        "space": "O(n)",
        "techniques": "Sentinel nodes; LRU cache construction",
        "wikipedia": "https://en.wikipedia.org/wiki/Doubly_linked_list",
        "resources": "https://www.geeksforgeeks.org/doubly-linked-list/",
        "sean_prashad": False,
        "grind75": True,
        "notes": "Backbone of LRU cache (combined with hash map).",
    },
    {
        "name": "Stack",
        "kind": "Data Structure",
        "category": "Linear",
        "definition": "LIFO container supporting push and pop at the top in O(1).",
        "time": "Push/Pop/Peek O(1)",
        "space": "O(n)",
        "techniques": "Recursion simulation; Monotonic stack; Parentheses matching; Function call tracking",
        "wikipedia": "https://en.wikipedia.org/wiki/Stack_(abstract_data_type)",
        "resources": "https://www.techinterviewhandbook.org/algorithms/stack/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If recursion is banned → Stack.'",
    },
    {
        "name": "Queue",
        "kind": "Data Structure",
        "category": "Linear",
        "definition": "FIFO container; enqueue at the rear, dequeue at the front in O(1).",
        "time": "Enqueue/Dequeue O(1)",
        "space": "O(n)",
        "techniques": "BFS scheduling; Producer-consumer; Level-order traversal",
        "wikipedia": "https://en.wikipedia.org/wiki/Queue_(abstract_data_type)",
        "resources": "https://www.techinterviewhandbook.org/algorithms/queue/",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Used everywhere in BFS.",
    },
    {
        "name": "Deque (Double-ended queue)",
        "kind": "Data Structure",
        "category": "Linear",
        "definition": "Container with O(1) insert/remove at both ends; basis of monotonic queue.",
        "time": "Push/Pop both ends O(1)",
        "space": "O(n)",
        "techniques": "Monotonic deque; Sliding window max/min",
        "wikipedia": "https://en.wikipedia.org/wiki/Double-ended_queue",
        "resources": "https://docs.python.org/3/library/collections.html#collections.deque",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Sean Prashad: 'If asked for sliding window max/min → Monotonic queue.'",
    },
    {
        "name": "Hash Table / Hash Map",
        "kind": "Data Structure",
        "category": "Hash-based",
        "definition": "Key→value store using a hash function to map keys to buckets for ~O(1) lookup.",
        "time": "Insert/Lookup/Delete avg O(1), worst O(n)",
        "space": "O(n)",
        "techniques": "Separate chaining; Open addressing; Rolling hash; Counting; Memoization",
        "wikipedia": "https://en.wikipedia.org/wiki/Hash_table",
        "resources": "https://www.techinterviewhandbook.org/algorithms/hash-table/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If need O(1) lookup → Hash table, Hash set.' Most common DS in interviews.",
    },
    {
        "name": "Hash Set",
        "kind": "Data Structure",
        "category": "Hash-based",
        "definition": "Unordered set of unique keys backed by a hash function.",
        "time": "Insert/Lookup/Delete avg O(1)",
        "space": "O(n)",
        "techniques": "Duplicate detection; Set intersection; Visited tracking",
        "wikipedia": "https://en.wikipedia.org/wiki/Set_(abstract_data_type)",
        "resources": "https://www.geeksforgeeks.org/hash-set-in-java/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Default visited-tracker in DFS/BFS.",
    },
    {
        "name": "Bloom Filter",
        "kind": "Data Structure",
        "category": "Hash-based",
        "definition": "Probabilistic set with no false negatives and tunable false positives, using k hash functions.",
        "time": "Insert/Lookup O(k)",
        "space": "O(m) bits",
        "techniques": "Multiple hash functions; Bit array",
        "wikipedia": "https://en.wikipedia.org/wiki/Bloom_filter",
        "resources": "https://systemdesign.io/bloom-filters/",
        "sean_prashad": False,
        "grind75": False,
        "notes": "System design favourite — caches, DB membership checks.",
    },
    # ============================================================
    # DATA STRUCTURES — Trees
    # ============================================================
    {
        "name": "Binary Tree",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Tree where each node has at most two children (left, right).",
        "time": "Traversal O(n)",
        "space": "O(n)",
        "techniques": "DFS (pre/in/post-order); BFS (level order); Recursion; Morris traversal",
        "wikipedia": "https://en.wikipedia.org/wiki/Binary_tree",
        "resources": "https://www.techinterviewhandbook.org/algorithms/tree/ | https://visualgo.net/en/bst",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If given a tree → DFS, BFS.'",
    },
    {
        "name": "Binary Search Tree (BST)",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Binary tree where left subtree < node < right subtree, giving O(log n) search if balanced.",
        "time": "Search/Insert/Delete avg O(log n), worst O(n)",
        "space": "O(n)",
        "techniques": "In-order traversal yields sorted sequence; Validation via bounds",
        "wikipedia": "https://en.wikipedia.org/wiki/Binary_search_tree",
        "resources": "https://visualgo.net/en/bst",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Watch for degenerate skewed BST → use self-balancing in practice.",
    },
    {
        "name": "AVL Tree",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Self-balancing BST where heights of children differ by at most 1; rebalances via rotations.",
        "time": "All ops O(log n)",
        "space": "O(n)",
        "techniques": "Rotations; Height balancing",
        "wikipedia": "https://en.wikipedia.org/wiki/AVL_tree",
        "resources": "https://visualgo.net/en/bst",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Conceptual — interview-relevant for 'how does std::map work?' style questions.",
    },
    {
        "name": "Red-Black Tree",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Self-balancing BST using node colours and 5 invariants to guarantee O(log n).",
        "time": "All ops O(log n)",
        "space": "O(n)",
        "techniques": "Recolouring; Rotations",
        "wikipedia": "https://en.wikipedia.org/wiki/Red%E2%80%93black_tree",
        "resources": "https://www.geeksforgeeks.org/introduction-to-red-black-tree/",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Backs Java TreeMap, C++ std::map.",
    },
    {
        "name": "B-Tree / B+ Tree",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Multi-way balanced search tree optimized for block-based storage (databases, filesystems).",
        "time": "All ops O(log n)",
        "space": "O(n)",
        "techniques": "Node splitting; Disk-friendly layout",
        "wikipedia": "https://en.wikipedia.org/wiki/B-tree",
        "resources": "https://en.wikipedia.org/wiki/B%2B_tree",
        "sean_prashad": False,
        "grind75": False,
        "notes": "System design / database internals topic.",
    },
    {
        "name": "Trie (Prefix Tree)",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Tree where each path from root encodes a string; O(L) insert/lookup for length-L key.",
        "time": "Insert/Search O(L)",
        "space": "O(N·L·alphabet)",
        "techniques": "Prefix matching; Autocomplete; Word search backtracking",
        "wikipedia": "https://en.wikipedia.org/wiki/Trie",
        "resources": "https://www.techinterviewhandbook.org/algorithms/trie/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If asked for common strings → Map, Trie.'",
    },
    {
        "name": "Heap (Binary Heap)",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Complete binary tree satisfying heap property (min or max at root); array-backed.",
        "time": "Insert/Pop O(log n) · Peek O(1)",
        "space": "O(n)",
        "techniques": "Sift up/down; Heapify; Top-K; Heap sort",
        "wikipedia": "https://en.wikipedia.org/wiki/Heap_(data_structure)",
        "resources": "https://www.techinterviewhandbook.org/algorithms/heap/ | https://visualgo.net/en/heap",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If asked for top/least K items → Heap, Quickselect, Bucket sort.'",
    },
    {
        "name": "Priority Queue",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Abstract queue ordered by priority; typically a binary heap underneath.",
        "time": "Insert/Pop O(log n)",
        "space": "O(n)",
        "techniques": "Dijkstra; Median of stream; Merge K sorted",
        "wikipedia": "https://en.wikipedia.org/wiki/Priority_queue",
        "resources": "https://docs.python.org/3/library/heapq.html",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Java PriorityQueue, Python heapq.",
    },
    {
        "name": "Segment Tree",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Tree over array intervals supporting range queries and point/range updates.",
        "time": "Build O(n) · Query/Update O(log n)",
        "space": "O(n)",
        "techniques": "Lazy propagation; Range sum/min/max",
        "wikipedia": "https://en.wikipedia.org/wiki/Segment_tree",
        "resources": "https://cp-algorithms.com/data_structures/segment_tree.html",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Sean Prashad: 'If need range sum/frequency queries → Prefix sum, Binary indexed tree, Segment tree.'",
    },
    {
        "name": "Fenwick Tree (Binary Indexed Tree)",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Compact array structure giving prefix sums with O(log n) update and query.",
        "time": "Update/Query O(log n)",
        "space": "O(n)",
        "techniques": "Low-bit trick; Range sum",
        "wikipedia": "https://en.wikipedia.org/wiki/Fenwick_tree",
        "resources": "https://cp-algorithms.com/data_structures/fenwick.html",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Lighter than segment tree when only prefix sums needed.",
    },
    {
        "name": "Disjoint Set Union (Union-Find)",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Partition of elements into disjoint sets supporting near-O(1) union and find.",
        "time": "Union/Find amortized ~O(α(n))",
        "space": "O(n)",
        "techniques": "Path compression; Union by rank/size",
        "wikipedia": "https://en.wikipedia.org/wiki/Disjoint-set_data_structure",
        "resources": "https://cp-algorithms.com/data_structures/disjoint_set_union.html",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If asked for connectivity/grouping → Union-Find, DFS.'",
    },
    {
        "name": "Suffix Array / Suffix Tree",
        "kind": "Data Structure",
        "category": "Trees",
        "definition": "Sorted array (or compressed tree) of all suffixes of a string; powers fast substring queries.",
        "time": "Build O(n log n) · Query O(m + log n)",
        "space": "O(n)",
        "techniques": "DC3 algorithm; LCP array",
        "wikipedia": "https://en.wikipedia.org/wiki/Suffix_array",
        "resources": "https://cp-algorithms.com/string/suffix-array.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Advanced; rare in standard interviews but common in competitive programming.",
    },
    # ============================================================
    # DATA STRUCTURES — Graph
    # ============================================================
    {
        "name": "Graph",
        "kind": "Data Structure",
        "category": "Graph",
        "definition": "Set of vertices (nodes) and edges; can be directed/undirected, weighted/unweighted, cyclic/acyclic.",
        "time": "Varies by algorithm",
        "space": "Adj list O(V+E) · Adj matrix O(V^2)",
        "techniques": "BFS; DFS; Union-Find; Topological sort; Dijkstra; Bellman-Ford",
        "wikipedia": "https://en.wikipedia.org/wiki/Graph_(abstract_data_type)",
        "resources": "https://www.techinterviewhandbook.org/algorithms/graph/ | https://visualgo.net/en/graphds",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If given a graph → DFS, BFS, Union-Find.'",
    },
    {
        "name": "Matrix (Grid)",
        "kind": "Data Structure",
        "category": "Graph",
        "definition": "2D array often treated as an implicit graph; cells = nodes, adjacency = neighbours.",
        "time": "Traversal O(rows·cols)",
        "space": "O(rows·cols)",
        "techniques": "BFS; DFS; DP on grid; Flood fill",
        "wikipedia": "https://en.wikipedia.org/wiki/Matrix_(mathematics)",
        "resources": "https://www.techinterviewhandbook.org/algorithms/matrix/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If given a matrix → BFS, DFS, Dynamic programming.'",
    },
    # ============================================================
    # DATA STRUCTURES — Specialized
    # ============================================================
    {
        "name": "Monotonic Stack",
        "kind": "Data Structure",
        "category": "Specialized",
        "definition": "Stack whose elements are kept in monotonic order; used for next-greater/smaller-element problems.",
        "time": "Each element pushed/popped once → O(n)",
        "space": "O(n)",
        "techniques": "Next greater / smaller element; Histogram largest rectangle",
        "wikipedia": "https://en.wikipedia.org/wiki/Monotonic_function",
        "resources": "https://liuzhenglaichn.gitbook.io/algorithm/monotonic-stack",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Sean Prashad: 'If asked for next greater/smaller element → Monotonic stack.'",
    },
    {
        "name": "Monotonic Queue / Deque",
        "kind": "Data Structure",
        "category": "Specialized",
        "definition": "Deque maintained in monotonic order so the front is always the max/min of the current window.",
        "time": "Amortized O(1) per element",
        "space": "O(window)",
        "techniques": "Sliding window max/min",
        "wikipedia": "https://en.wikipedia.org/wiki/Double-ended_queue",
        "resources": "https://leetcode.com/problems/sliding-window-maximum/",
        "sean_prashad": True,
        "grind75": False,
        "notes": "LeetCode 239 is the canonical use-case.",
    },
    {
        "name": "LRU Cache",
        "kind": "Data Structure",
        "category": "Specialized",
        "definition": "Cache that evicts the least-recently-used entry; canonical implementation is hash map + doubly linked list.",
        "time": "Get/Put O(1)",
        "space": "O(capacity)",
        "techniques": "Hash map + Doubly linked list",
        "wikipedia": "https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)",
        "resources": "https://leetcode.com/problems/lru-cache/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If given a stream of data → Heap, Design.' Classic design question.",
    },
    {
        "name": "Skip List",
        "kind": "Data Structure",
        "category": "Specialized",
        "definition": "Probabilistic data structure of sorted linked lists with multiple levels giving O(log n) ops.",
        "time": "Search/Insert/Delete avg O(log n)",
        "space": "O(n)",
        "techniques": "Randomized levels",
        "wikipedia": "https://en.wikipedia.org/wiki/Skip_list",
        "resources": "https://www.geeksforgeeks.org/skip-list/",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Redis sorted sets are built on skip lists.",
    },
    {
        "name": "Sparse Table",
        "kind": "Data Structure",
        "category": "Specialized",
        "definition": "Precomputed table that answers immutable range min/max/gcd queries in O(1) after O(n log n) prep.",
        "time": "Build O(n log n) · Query O(1)",
        "space": "O(n log n)",
        "techniques": "Doubling; Idempotent operations only",
        "wikipedia": "https://en.wikipedia.org/wiki/Range_minimum_query",
        "resources": "https://cp-algorithms.com/data_structures/sparse-table.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Range min/max query specialty.",
    },
    # ============================================================
    # ALGORITHMS — Searching
    # ============================================================
    {
        "name": "Linear Search",
        "kind": "Algorithm",
        "category": "Searching",
        "definition": "Scan the collection element-by-element until target is found.",
        "time": "O(n)",
        "space": "O(1)",
        "techniques": "Brute force baseline",
        "wikipedia": "https://en.wikipedia.org/wiki/Linear_search",
        "resources": "https://en.wikipedia.org/wiki/Linear_search",
        "sean_prashad": False,
        "grind75": True,
        "notes": "Baseline to beat.",
    },
    {
        "name": "Binary Search",
        "kind": "Algorithm",
        "category": "Searching",
        "definition": "Repeatedly halve a sorted range to locate a target in O(log n).",
        "time": "O(log n)",
        "space": "O(1) iterative",
        "techniques": "Two pointers (lo/hi); Binary search on answer; Lower/upper bound",
        "wikipedia": "https://en.wikipedia.org/wiki/Binary_search_algorithm",
        "resources": "https://www.techinterviewhandbook.org/algorithms/binary-search/ | https://leetcode.com/explore/learn/card/binary-search/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If input array is sorted → Binary search, Two pointers.' Also 'binary search on answer' pattern.",
    },
    {
        "name": "Ternary Search",
        "kind": "Algorithm",
        "category": "Searching",
        "definition": "Search a unimodal function by splitting into thirds.",
        "time": "O(log n)",
        "space": "O(1)",
        "techniques": "Unimodal optimization",
        "wikipedia": "https://en.wikipedia.org/wiki/Ternary_search",
        "resources": "https://cp-algorithms.com/num_methods/ternary_search.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Useful for finding extrema of unimodal functions.",
    },
    {
        "name": "Quickselect",
        "kind": "Algorithm",
        "category": "Searching",
        "definition": "Partition-based selection of the k-th smallest element in average O(n).",
        "time": "Avg O(n), worst O(n^2)",
        "space": "O(1)",
        "techniques": "Lomuto/Hoare partition; Randomized pivot",
        "wikipedia": "https://en.wikipedia.org/wiki/Quickselect",
        "resources": "https://en.wikipedia.org/wiki/Quickselect",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Often beats a heap for one-shot top-K.",
    },
    # ============================================================
    # ALGORITHMS — Sorting
    # ============================================================
    {
        "name": "Bubble Sort",
        "kind": "Algorithm",
        "category": "Sorting",
        "definition": "Repeatedly swap adjacent out-of-order pairs until sorted.",
        "time": "O(n^2)",
        "space": "O(1)",
        "techniques": "Adjacent swaps",
        "wikipedia": "https://en.wikipedia.org/wiki/Bubble_sort",
        "resources": "https://visualgo.net/en/sorting",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Educational only.",
    },
    {
        "name": "Insertion Sort",
        "kind": "Algorithm",
        "category": "Sorting",
        "definition": "Build the sorted list one element at a time by inserting into the correct position.",
        "time": "O(n^2), O(n) on nearly-sorted",
        "space": "O(1)",
        "techniques": "In-place; Stable; Online",
        "wikipedia": "https://en.wikipedia.org/wiki/Insertion_sort",
        "resources": "https://visualgo.net/en/sorting",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Good for tiny or nearly-sorted arrays.",
    },
    {
        "name": "Selection Sort",
        "kind": "Algorithm",
        "category": "Sorting",
        "definition": "Repeatedly select the minimum from the unsorted suffix and place it.",
        "time": "O(n^2)",
        "space": "O(1)",
        "techniques": "In-place",
        "wikipedia": "https://en.wikipedia.org/wiki/Selection_sort",
        "resources": "https://visualgo.net/en/sorting",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Educational only.",
    },
    {
        "name": "Merge Sort",
        "kind": "Algorithm",
        "category": "Sorting",
        "definition": "Divide-and-conquer sort: split, recursively sort halves, then merge.",
        "time": "O(n log n)",
        "space": "O(n)",
        "techniques": "Divide & conquer; Stable; Used for merging sorted lists",
        "wikipedia": "https://en.wikipedia.org/wiki/Merge_sort",
        "resources": "https://visualgo.net/en/sorting",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If asked to merge sorted lists/intervals → Merge sort, Heap.'",
    },
    {
        "name": "Quick Sort",
        "kind": "Algorithm",
        "category": "Sorting",
        "definition": "Pick a pivot, partition into smaller/greater, recurse; average O(n log n).",
        "time": "Avg O(n log n), worst O(n^2)",
        "space": "O(log n) recursion",
        "techniques": "Pivot selection; Partitioning",
        "wikipedia": "https://en.wikipedia.org/wiki/Quicksort",
        "resources": "https://visualgo.net/en/sorting",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Backbone of std::sort in many libraries (often introsort).",
    },
    {
        "name": "Heap Sort",
        "kind": "Algorithm",
        "category": "Sorting",
        "definition": "Build a max-heap, then repeatedly extract the max.",
        "time": "O(n log n)",
        "space": "O(1)",
        "techniques": "Heapify",
        "wikipedia": "https://en.wikipedia.org/wiki/Heapsort",
        "resources": "https://visualgo.net/en/sorting",
        "sean_prashad": True,
        "grind75": True,
        "notes": "In-place O(n log n) but not stable.",
    },
    {
        "name": "Counting Sort",
        "kind": "Algorithm",
        "category": "Sorting",
        "definition": "Non-comparison sort using counts per value; O(n+k) for small integer range k.",
        "time": "O(n + k)",
        "space": "O(k)",
        "techniques": "Bucketing by value",
        "wikipedia": "https://en.wikipedia.org/wiki/Counting_sort",
        "resources": "https://visualgo.net/en/sorting",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Beats O(n log n) when range is small.",
    },
    {
        "name": "Radix Sort",
        "kind": "Algorithm",
        "category": "Sorting",
        "definition": "Non-comparison sort: process digits/bits from least to most significant using stable counting sort.",
        "time": "O(d·(n+b))",
        "space": "O(n+b)",
        "techniques": "Digit-by-digit; Stable",
        "wikipedia": "https://en.wikipedia.org/wiki/Radix_sort",
        "resources": "https://en.wikipedia.org/wiki/Radix_sort",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Good for fixed-width integers and strings.",
    },
    {
        "name": "Bucket Sort",
        "kind": "Algorithm",
        "category": "Sorting",
        "definition": "Distribute elements into buckets, sort each, then concatenate.",
        "time": "Avg O(n+k)",
        "space": "O(n+k)",
        "techniques": "Bucket distribution",
        "wikipedia": "https://en.wikipedia.org/wiki/Bucket_sort",
        "resources": "https://en.wikipedia.org/wiki/Bucket_sort",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Sean Prashad: 'If asked for top/least K → Heap, Quickselect, Bucket sort.' Used in Top-K Frequent.",
    },
    {
        "name": "Topological Sort",
        "kind": "Algorithm",
        "category": "Sorting",
        "definition": "Linear ordering of a DAG's vertices such that for every edge u→v, u precedes v.",
        "time": "O(V+E)",
        "space": "O(V)",
        "techniques": "Kahn's (BFS, in-degree); DFS post-order",
        "wikipedia": "https://en.wikipedia.org/wiki/Topological_sorting",
        "resources": "https://cp-algorithms.com/graph/topological-sort.html",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If asked for ordering/scheduling → Topological sort.'",
    },
    # ============================================================
    # ALGORITHMS — Graph traversal & shortest path
    # ============================================================
    {
        "name": "Breadth-First Search (BFS)",
        "kind": "Algorithm",
        "category": "Graph traversal",
        "definition": "Level-by-level graph traversal using a queue; finds shortest path in unweighted graphs.",
        "time": "O(V+E)",
        "space": "O(V)",
        "techniques": "Queue; Visited set; Level tracking",
        "wikipedia": "https://en.wikipedia.org/wiki/Breadth-first_search",
        "resources": "https://visualgo.net/en/dfsbfs",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Shortest path in unweighted graph; level-order on trees.",
    },
    {
        "name": "Depth-First Search (DFS)",
        "kind": "Algorithm",
        "category": "Graph traversal",
        "definition": "Explore as far as possible along each branch before backtracking; recursion or stack.",
        "time": "O(V+E)",
        "space": "O(V)",
        "techniques": "Recursion; Stack; Visited set; Backtracking",
        "wikipedia": "https://en.wikipedia.org/wiki/Depth-first_search",
        "resources": "https://visualgo.net/en/dfsbfs",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Foundation of cycle detection, connectivity, topological sort.",
    },
    {
        "name": "Dijkstra's Algorithm",
        "kind": "Algorithm",
        "category": "Shortest path",
        "definition": "Single-source shortest paths in weighted graph with non-negative edges using a priority queue.",
        "time": "O((V+E) log V)",
        "space": "O(V)",
        "techniques": "Priority queue; Greedy relaxation",
        "wikipedia": "https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm",
        "resources": "https://visualgo.net/en/sssp",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Standard for weighted shortest paths when no negative edges.",
    },
    {
        "name": "Bellman-Ford",
        "kind": "Algorithm",
        "category": "Shortest path",
        "definition": "Single-source shortest paths allowing negative weights; detects negative cycles.",
        "time": "O(V·E)",
        "space": "O(V)",
        "techniques": "Edge relaxation V-1 times",
        "wikipedia": "https://en.wikipedia.org/wiki/Bellman%E2%80%93Ford_algorithm",
        "resources": "https://cp-algorithms.com/graph/bellman_ford.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Use when negative weights are possible.",
    },
    {
        "name": "Floyd-Warshall",
        "kind": "Algorithm",
        "category": "Shortest path",
        "definition": "All-pairs shortest paths via DP over intermediate vertices.",
        "time": "O(V^3)",
        "space": "O(V^2)",
        "techniques": "DP triple loop",
        "wikipedia": "https://en.wikipedia.org/wiki/Floyd%E2%80%93Warshall_algorithm",
        "resources": "https://cp-algorithms.com/graph/all-pair-shortest-path-floyd-warshall.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Good when V is small (≤500) and you need all pairs.",
    },
    {
        "name": "A* Search",
        "kind": "Algorithm",
        "category": "Shortest path",
        "definition": "Best-first search using f(n) = g(n) + h(n); admissible heuristic yields optimal path.",
        "time": "Depends on heuristic; O(E) at best",
        "space": "O(V)",
        "techniques": "Heuristic search; Priority queue",
        "wikipedia": "https://en.wikipedia.org/wiki/A*_search_algorithm",
        "resources": "https://www.redblobgames.com/pathfinding/a-star/introduction.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Pathfinding in games and AI.",
    },
    {
        "name": "Kruskal's MST",
        "kind": "Algorithm",
        "category": "Graph",
        "definition": "Build minimum spanning tree by sorting edges and adding via union-find.",
        "time": "O(E log E)",
        "space": "O(V)",
        "techniques": "Sort edges; Union-Find",
        "wikipedia": "https://en.wikipedia.org/wiki/Kruskal%27s_algorithm",
        "resources": "https://cp-algorithms.com/graph/mst_kruskal.html",
        "sean_prashad": True,
        "grind75": False,
        "notes": "MST when edge list is given.",
    },
    {
        "name": "Prim's MST",
        "kind": "Algorithm",
        "category": "Graph",
        "definition": "Grow MST by repeatedly adding the cheapest edge to the growing component.",
        "time": "O((V+E) log V)",
        "space": "O(V)",
        "techniques": "Priority queue; Visited set",
        "wikipedia": "https://en.wikipedia.org/wiki/Prim%27s_algorithm",
        "resources": "https://cp-algorithms.com/graph/mst_prim.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "MST when adjacency-list is given.",
    },
    {
        "name": "Tarjan's SCC",
        "kind": "Algorithm",
        "category": "Graph",
        "definition": "Find strongly connected components in a directed graph in O(V+E) using DFS lowlinks.",
        "time": "O(V+E)",
        "space": "O(V)",
        "techniques": "DFS lowlink; Stack",
        "wikipedia": "https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm",
        "resources": "https://cp-algorithms.com/graph/strongly-connected-components.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Advanced; useful for 2-SAT and dependency analysis.",
    },
    {
        "name": "Kosaraju's SCC",
        "kind": "Algorithm",
        "category": "Graph",
        "definition": "Find SCCs with two DFS passes: original graph then reversed graph.",
        "time": "O(V+E)",
        "space": "O(V)",
        "techniques": "DFS; Reverse graph",
        "wikipedia": "https://en.wikipedia.org/wiki/Kosaraju%27s_algorithm",
        "resources": "https://cp-algorithms.com/graph/strongly-connected-components.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Simpler than Tarjan to implement.",
    },
    {
        "name": "Floyd's Cycle Detection (Tortoise & Hare)",
        "kind": "Algorithm",
        "category": "Graph",
        "definition": "Detect a cycle in a linked list / functional graph using two pointers at different speeds.",
        "time": "O(n)",
        "space": "O(1)",
        "techniques": "Fast & slow pointers",
        "wikipedia": "https://en.wikipedia.org/wiki/Cycle_detection",
        "resources": "https://leetcode.com/problems/linked-list-cycle-ii/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Canonical 'fast & slow pointers' pattern.",
    },
    # ============================================================
    # ALGORITHMS — Dynamic Programming
    # ============================================================
    {
        "name": "Dynamic Programming",
        "kind": "Paradigm",
        "category": "Dynamic Programming",
        "definition": "Solve problems by combining solutions to overlapping subproblems; top-down (memo) or bottom-up (table).",
        "time": "Problem-specific",
        "space": "Problem-specific",
        "techniques": "Memoization; Tabulation; State design; Optimal substructure",
        "wikipedia": "https://en.wikipedia.org/wiki/Dynamic_programming",
        "resources": "https://www.techinterviewhandbook.org/algorithms/dynamic-programming/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If asked for max/min subarray/subset → DP, Sliding window.'",
    },
    {
        "name": "Knapsack (0/1)",
        "kind": "Algorithm",
        "category": "Dynamic Programming",
        "definition": "Choose items with weights and values to maximize value under a weight cap; each item once.",
        "time": "O(n·W)",
        "space": "O(n·W) or O(W)",
        "techniques": "2D DP; Space-optimised 1D backward",
        "wikipedia": "https://en.wikipedia.org/wiki/Knapsack_problem",
        "resources": "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Subset sum, partition equal subset sum are reductions.",
    },
    {
        "name": "Unbounded Knapsack",
        "kind": "Algorithm",
        "category": "Dynamic Programming",
        "definition": "Knapsack variant allowing unlimited copies of each item.",
        "time": "O(n·W)",
        "space": "O(W)",
        "techniques": "1D DP, forward iteration",
        "wikipedia": "https://en.wikipedia.org/wiki/Knapsack_problem#Unbounded_knapsack_problem",
        "resources": "https://www.geeksforgeeks.org/unbounded-knapsack-repetition-items-allowed/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Coin change is a special case.",
    },
    {
        "name": "Longest Common Subsequence (LCS)",
        "kind": "Algorithm",
        "category": "Dynamic Programming",
        "definition": "Find longest sequence appearing in both strings in the same order (not necessarily contiguous).",
        "time": "O(n·m)",
        "space": "O(n·m) or O(min(n,m))",
        "techniques": "2D DP table",
        "wikipedia": "https://en.wikipedia.org/wiki/Longest_common_subsequence_problem",
        "resources": "https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Edit distance variant.",
    },
    {
        "name": "Longest Increasing Subsequence (LIS)",
        "kind": "Algorithm",
        "category": "Dynamic Programming",
        "definition": "Find the longest strictly increasing subsequence; O(n log n) with patience sorting.",
        "time": "O(n log n)",
        "space": "O(n)",
        "techniques": "DP + binary search (patience sort)",
        "wikipedia": "https://en.wikipedia.org/wiki/Longest_increasing_subsequence",
        "resources": "https://leetcode.com/problems/longest-increasing-subsequence/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Russian doll envelopes is a 2D variant.",
    },
    {
        "name": "Edit Distance (Levenshtein)",
        "kind": "Algorithm",
        "category": "Dynamic Programming",
        "definition": "Minimum number of insert/delete/replace operations to transform one string into another.",
        "time": "O(n·m)",
        "space": "O(n·m)",
        "techniques": "2D DP",
        "wikipedia": "https://en.wikipedia.org/wiki/Levenshtein_distance",
        "resources": "https://leetcode.com/problems/edit-distance/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Foundational string DP.",
    },
    {
        "name": "Matrix Chain Multiplication",
        "kind": "Algorithm",
        "category": "Dynamic Programming",
        "definition": "Find the cheapest way to parenthesize a chain of matrix multiplications.",
        "time": "O(n^3)",
        "space": "O(n^2)",
        "techniques": "Interval DP",
        "wikipedia": "https://en.wikipedia.org/wiki/Matrix_chain_multiplication",
        "resources": "https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Classic interval DP teaching example.",
    },
    {
        "name": "Bitmask DP",
        "kind": "Algorithm",
        "category": "Dynamic Programming",
        "definition": "DP where state encodes a subset as bits in an integer; common for TSP-like problems on small n.",
        "time": "O(2^n · n)",
        "space": "O(2^n)",
        "techniques": "Subset enumeration via bits",
        "wikipedia": "https://en.wikipedia.org/wiki/Bitmask",
        "resources": "https://cp-algorithms.com/dynamic_programming/profile-dynamics.html",
        "sean_prashad": True,
        "grind75": True,
        "notes": "n ≤ ~20.",
    },
    # ============================================================
    # ALGORITHMS — Greedy
    # ============================================================
    {
        "name": "Greedy Algorithm",
        "kind": "Paradigm",
        "category": "Greedy",
        "definition": "Build a solution by always taking the locally optimal choice; works when the problem has the greedy-choice property.",
        "time": "Problem-specific",
        "space": "Problem-specific",
        "techniques": "Exchange argument; Sort then scan",
        "wikipedia": "https://en.wikipedia.org/wiki/Greedy_algorithm",
        "resources": "https://www.techinterviewhandbook.org/algorithms/greedy/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If need to count/divide optimally → Greedy, DP.'",
    },
    {
        "name": "Interval Scheduling",
        "kind": "Algorithm",
        "category": "Greedy",
        "definition": "Select the maximum number of non-overlapping intervals; sort by end time and scan.",
        "time": "O(n log n)",
        "space": "O(1)",
        "techniques": "Sort by end time",
        "wikipedia": "https://en.wikipedia.org/wiki/Interval_scheduling",
        "resources": "https://leetcode.com/problems/non-overlapping-intervals/",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Sean Prashad: 'If asked for overlapping intervals → Sorting, Sweep line.'",
    },
    {
        "name": "Huffman Coding",
        "kind": "Algorithm",
        "category": "Greedy",
        "definition": "Build optimal prefix code by repeatedly merging two least-frequent symbols.",
        "time": "O(n log n)",
        "space": "O(n)",
        "techniques": "Min-heap",
        "wikipedia": "https://en.wikipedia.org/wiki/Huffman_coding",
        "resources": "https://www.geeksforgeeks.org/huffman-coding-greedy-algo-3/",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Compression classic.",
    },
    # ============================================================
    # ALGORITHMS — Divide & Conquer
    # ============================================================
    {
        "name": "Divide & Conquer",
        "kind": "Paradigm",
        "category": "Divide & Conquer",
        "definition": "Solve by splitting problem into subproblems, recursing, and combining results.",
        "time": "Master theorem dependent",
        "space": "Recursion depth",
        "techniques": "Recursion; Master theorem",
        "wikipedia": "https://en.wikipedia.org/wiki/Divide-and-conquer_algorithm",
        "resources": "https://en.wikipedia.org/wiki/Master_theorem_(analysis_of_algorithms)",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Powers merge sort, quick sort, FFT, Karatsuba.",
    },
    # ============================================================
    # ALGORITHMS — Backtracking
    # ============================================================
    {
        "name": "Backtracking",
        "kind": "Paradigm",
        "category": "Backtracking",
        "definition": "Build a solution incrementally and undo choices that lead to dead ends.",
        "time": "Often O(b^d) where b=branches, d=depth",
        "space": "O(d)",
        "techniques": "DFS with undo; Pruning",
        "wikipedia": "https://en.wikipedia.org/wiki/Backtracking",
        "resources": "https://leetcode.com/discuss/general-discussion/680706/backtracking-cheat-sheet",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If asked for all permutations/subsets → Backtracking.'",
    },
    {
        "name": "N-Queens",
        "kind": "Algorithm",
        "category": "Backtracking",
        "definition": "Place N non-attacking queens on an N×N board via backtracking with column/diagonal pruning.",
        "time": "O(N!)",
        "space": "O(N)",
        "techniques": "Backtracking; Bit masks for diagonals",
        "wikipedia": "https://en.wikipedia.org/wiki/Eight_queens_puzzle",
        "resources": "https://leetcode.com/problems/n-queens/",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Canonical backtracking exercise.",
    },
    {
        "name": "Permutations / Combinations / Subsets",
        "kind": "Algorithm",
        "category": "Backtracking",
        "definition": "Enumerate all permutations, combinations, or subsets of a collection.",
        "time": "O(n·n!), O(n·2^n)",
        "space": "O(n)",
        "techniques": "Backtracking; Bit enumeration",
        "wikipedia": "https://en.wikipedia.org/wiki/Permutation",
        "resources": "https://leetcode.com/tag/backtracking/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Pattern: choose / explore / unchoose.",
    },
    # ============================================================
    # ALGORITHMS — String
    # ============================================================
    {
        "name": "KMP (Knuth-Morris-Pratt)",
        "kind": "Algorithm",
        "category": "String",
        "definition": "Linear-time substring search using a failure function (LPS array).",
        "time": "O(n+m)",
        "space": "O(m)",
        "techniques": "LPS prefix function",
        "wikipedia": "https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm",
        "resources": "https://cp-algorithms.com/string/prefix-function.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Substring search and longest proper prefix/suffix problems.",
    },
    {
        "name": "Rabin-Karp",
        "kind": "Algorithm",
        "category": "String",
        "definition": "Substring search using rolling hash; great for multiple patterns.",
        "time": "Avg O(n+m), worst O(n·m)",
        "space": "O(1)",
        "techniques": "Rolling hash; Modular arithmetic",
        "wikipedia": "https://en.wikipedia.org/wiki/Rabin%E2%80%93Karp_algorithm",
        "resources": "https://cp-algorithms.com/string/rabin-karp.html",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Use double hashing to avoid collisions.",
    },
    {
        "name": "Z Algorithm",
        "kind": "Algorithm",
        "category": "String",
        "definition": "Compute Z-array (length of longest substring starting at i matching a prefix) in O(n).",
        "time": "O(n+m)",
        "space": "O(n)",
        "techniques": "Z-box",
        "wikipedia": "https://en.wikipedia.org/wiki/Z-function",
        "resources": "https://cp-algorithms.com/string/z-function.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Alternative to KMP.",
    },
    {
        "name": "Manacher's Algorithm",
        "kind": "Algorithm",
        "category": "String",
        "definition": "Find all palindromic substrings in linear time.",
        "time": "O(n)",
        "space": "O(n)",
        "techniques": "Center expansion with reuse",
        "wikipedia": "https://en.wikipedia.org/wiki/Longest_palindromic_substring",
        "resources": "https://cp-algorithms.com/string/manacher.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Longest palindromic substring in O(n).",
    },
    {
        "name": "Aho-Corasick",
        "kind": "Algorithm",
        "category": "String",
        "definition": "Multi-pattern matching using a trie augmented with failure links.",
        "time": "O(n + m + z)",
        "space": "O(m)",
        "techniques": "Trie + BFS failure links",
        "wikipedia": "https://en.wikipedia.org/wiki/Aho%E2%80%93Corasick_algorithm",
        "resources": "https://cp-algorithms.com/string/aho_corasick.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Antivirus signature scanning; multi-pattern matching.",
    },
    # ============================================================
    # ALGORITHMS — Math
    # ============================================================
    {
        "name": "Euclidean Algorithm (GCD)",
        "kind": "Algorithm",
        "category": "Math",
        "definition": "Compute greatest common divisor via gcd(a,b) = gcd(b, a mod b).",
        "time": "O(log min(a,b))",
        "space": "O(1)",
        "techniques": "Recursion or iteration",
        "wikipedia": "https://en.wikipedia.org/wiki/Euclidean_algorithm",
        "resources": "https://cp-algorithms.com/algebra/euclid-algorithm.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Extended Euclidean also computes Bézout coefficients.",
    },
    {
        "name": "Sieve of Eratosthenes",
        "kind": "Algorithm",
        "category": "Math",
        "definition": "Find all primes up to N by iteratively marking multiples.",
        "time": "O(N log log N)",
        "space": "O(N)",
        "techniques": "Boolean sieve",
        "wikipedia": "https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes",
        "resources": "https://cp-algorithms.com/algebra/sieve-of-eratosthenes.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Linear sieve variant runs in O(N).",
    },
    {
        "name": "Fast Exponentiation",
        "kind": "Algorithm",
        "category": "Math",
        "definition": "Compute a^n in O(log n) via repeated squaring; works on integers and matrices.",
        "time": "O(log n)",
        "space": "O(1)",
        "techniques": "Binary exponentiation",
        "wikipedia": "https://en.wikipedia.org/wiki/Exponentiation_by_squaring",
        "resources": "https://cp-algorithms.com/algebra/binary-exp.html",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Matrix exponentiation accelerates linear recurrences.",
    },
    {
        "name": "Bit Manipulation",
        "kind": "Technique",
        "category": "Math",
        "definition": "Solve problems using bitwise AND/OR/XOR/shift tricks.",
        "time": "Usually O(1) per op",
        "space": "O(1)",
        "techniques": "XOR pairing; n & (n-1) lowest-bit; Bitmasks; Brian Kernighan's",
        "wikipedia": "https://en.wikipedia.org/wiki/Bit_manipulation",
        "resources": "https://leetcode.com/discuss/general-discussion/1073221/all-about-bitwise-operations-beginner-intermediate",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If asked to count bits or use XOR → Bit manipulation.'",
    },
    # ============================================================
    # PATTERNS / TECHNIQUES
    # ============================================================
    {
        "name": "Two Pointers",
        "kind": "Technique",
        "category": "Pattern",
        "definition": "Use two indices moving through an array/string in coordinated fashion; opposite ends or same direction.",
        "time": "O(n)",
        "space": "O(1)",
        "techniques": "Opposite-ends; Same-direction; Fast & slow",
        "wikipedia": "https://en.wikipedia.org/wiki/Two_pointers_technique",
        "resources": "https://leetcode.com/articles/two-pointer-technique/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If input sorted / given a linked list → Two pointers.'",
    },
    {
        "name": "Sliding Window",
        "kind": "Technique",
        "category": "Pattern",
        "definition": "Maintain a window over a contiguous range that grows/shrinks while tracking aggregate state.",
        "time": "O(n)",
        "space": "O(1) to O(window)",
        "techniques": "Fixed window; Variable window; Hash map state",
        "wikipedia": "https://en.wikipedia.org/wiki/Sliding_window_protocol",
        "resources": "https://leetcode.com/tag/sliding-window/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If asked for max/min subarray/subset → DP, Sliding window.'",
    },
    {
        "name": "Fast & Slow Pointers",
        "kind": "Technique",
        "category": "Pattern",
        "definition": "Two pointers advancing at different speeds — detects cycles, finds middle, etc.",
        "time": "O(n)",
        "space": "O(1)",
        "techniques": "Floyd's cycle detection; Find middle of LL",
        "wikipedia": "https://en.wikipedia.org/wiki/Cycle_detection#Floyd's_tortoise_and_hare",
        "resources": "https://leetcode.com/problems/linked-list-cycle/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Linked list cycle problems.",
    },
    {
        "name": "Prefix Sum",
        "kind": "Technique",
        "category": "Pattern",
        "definition": "Precompute cumulative sums so any range sum is answered in O(1).",
        "time": "Build O(n) · Query O(1)",
        "space": "O(n)",
        "techniques": "1D and 2D prefix; Hash-map prefix for subarray sums",
        "wikipedia": "https://en.wikipedia.org/wiki/Prefix_sum",
        "resources": "https://leetcode.com/tag/prefix-sum/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Sean Prashad: 'If need range sum/frequency queries → Prefix sum, BIT, Segment tree.'",
    },
    {
        "name": "Difference Array",
        "kind": "Technique",
        "category": "Pattern",
        "definition": "Apply range updates in O(1) and reconstruct array in O(n) via prefix-sum.",
        "time": "Update O(1) · Build O(n)",
        "space": "O(n)",
        "techniques": "Range increment trick",
        "wikipedia": "https://en.wikipedia.org/wiki/Prefix_sum",
        "resources": "https://leetcode.com/problems/range-addition/",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Inverse of prefix sum for range updates.",
    },
    {
        "name": "Sweep Line",
        "kind": "Technique",
        "category": "Pattern",
        "definition": "Sort events by coordinate then sweep, maintaining active set; common for interval problems.",
        "time": "O(n log n)",
        "space": "O(n)",
        "techniques": "Event sorting; Active set",
        "wikipedia": "https://en.wikipedia.org/wiki/Sweep_line_algorithm",
        "resources": "https://en.wikipedia.org/wiki/Sweep_line_algorithm",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Sean Prashad: 'If asked for overlapping intervals → Sorting, Sweep line.'",
    },
    {
        "name": "Recursion",
        "kind": "Paradigm",
        "category": "Pattern",
        "definition": "Solve a problem by reducing it to smaller instances of itself.",
        "time": "Problem-specific",
        "space": "O(depth) call stack",
        "techniques": "Base case; Recursive case; Tail recursion",
        "wikipedia": "https://en.wikipedia.org/wiki/Recursion_(computer_science)",
        "resources": "https://www.techinterviewhandbook.org/algorithms/recursion/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Foundation of DP, backtracking, tree/graph traversal.",
    },
    {
        "name": "Memoization",
        "kind": "Technique",
        "category": "Pattern",
        "definition": "Cache results of subproblem calls to avoid recomputation; top-down DP.",
        "time": "Problem-specific",
        "space": "O(states)",
        "techniques": "Hash map cache; Recursion + cache",
        "wikipedia": "https://en.wikipedia.org/wiki/Memoization",
        "resources": "https://en.wikipedia.org/wiki/Memoization",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Python's functools.lru_cache; manual map otherwise.",
    },
    {
        "name": "Flood Fill",
        "kind": "Algorithm",
        "category": "Pattern",
        "definition": "Fill connected region in a grid by recursively visiting neighbours of same value.",
        "time": "O(rows·cols)",
        "space": "O(rows·cols)",
        "techniques": "BFS or DFS on grid",
        "wikipedia": "https://en.wikipedia.org/wiki/Flood_fill",
        "resources": "https://leetcode.com/problems/flood-fill/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Number of islands, surrounded regions.",
    },
    {
        "name": "Reservoir Sampling",
        "kind": "Algorithm",
        "category": "Pattern",
        "definition": "Sample k items uniformly from a stream of unknown length.",
        "time": "O(n)",
        "space": "O(k)",
        "techniques": "Random replacement",
        "wikipedia": "https://en.wikipedia.org/wiki/Reservoir_sampling",
        "resources": "https://en.wikipedia.org/wiki/Reservoir_sampling",
        "sean_prashad": True,
        "grind75": False,
        "notes": "Sean Prashad: 'If given a stream of data → Heap, Design.'",
    },
    {
        "name": "Fisher-Yates Shuffle",
        "kind": "Algorithm",
        "category": "Pattern",
        "definition": "Uniformly random in-place shuffle in O(n).",
        "time": "O(n)",
        "space": "O(1)",
        "techniques": "Swap with random index",
        "wikipedia": "https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle",
        "resources": "https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle",
        "sean_prashad": False,
        "grind75": False,
        "notes": "Used in randomized quicksort and 'shuffle an array' problem.",
    },
    {
        "name": "Boyer-Moore Majority Vote",
        "kind": "Algorithm",
        "category": "Pattern",
        "definition": "Find majority element (>n/2) in O(n) time and O(1) space.",
        "time": "O(n)",
        "space": "O(1)",
        "techniques": "Counter cancellation",
        "wikipedia": "https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_majority_vote_algorithm",
        "resources": "https://leetcode.com/problems/majority-element/",
        "sean_prashad": False,
        "grind75": True,
        "notes": "Generalizes to k candidates for >n/k threshold.",
    },
    {
        "name": "Kadane's Algorithm",
        "kind": "Algorithm",
        "category": "Dynamic Programming",
        "definition": "Find maximum sum contiguous subarray in O(n) by tracking best ending here / best so far.",
        "time": "O(n)",
        "space": "O(1)",
        "techniques": "Rolling DP",
        "wikipedia": "https://en.wikipedia.org/wiki/Maximum_subarray_problem",
        "resources": "https://leetcode.com/problems/maximum-subarray/",
        "sean_prashad": True,
        "grind75": True,
        "notes": "Foundational subarray DP.",
    },
]
